spring.application.name=portfoliobase

tolgee.apiKey=tgpak_giytqnrwl5xdonrvnbstk5llgfsxizjshfzwenrzmvshizlinvyq
tolgee.apiUrl=https://app.tolgee.io/v2/projects/%s/translations
tolgee.project-id=21866

jwt.secret=your-very-secure-and-long-key-for-jwt-generation
# 1 day in milliseconds (1000*60*60*24)
jwt.expiration-time=86400000
jwt.key-name=pb_jwt